export const FETCH_LIST_LOGIC_PATTERN_CUSTOM = 'FETCH_LIST_LOGIC_PATTERN_CUSTOM';
export const SET_LIST_LOGIC_PATTERN_CUSTOM = 'SET_LIST_LOGIC_PATTERN_CUSTOM';

export const CREATE_OR_UPDATE_LOGIC_PATTERN = 'CREATE_OR_UPDATE_LOGIC_PATTERN';
export const GET_DETAIL_LOGIC_PATTERN_CUSTOM = 'GET_DETAIL_LOGIC_PATTERN_CUSTOM';
export const DELETE_LOGIC_PATTERN_CUSTOM = 'DELETE_LOGIC_PATTERN_CUSTOM';

export const FETCH_LIST_BET_PATTERN_CUSTOM = 'FETCH_LIST_BET_PATTERN_CUSTOM';
export const SET_LIST_BET_PATTERN_CUSTOM = 'SET_LIST_BET_PATTERN_CUSTOM';

export const GET_DETAIL_BET_PATTERN = 'GET_DETAIL_BET_PATTERN';
export const CREATE_OR_UPDATE_BET_PATTERN = 'CREATE_OR_UPDATE_BET_PATTERN';
export const DELETE_BET_PATTERN = 'DELETE_BET_PATTERN';

export const GET_SETTING_WORKER = 'GET_SETTING_WORKER';

export const LOGIC_PATTERN_DEFAULT_DATA = [{
  card_no: 1,
  bet_point: '',
  win_next: '',
  lose_next: '',
}];

export const BET_PATTERN_DEFAULT_DATA = [{
  card_no: 1,
  bet_value: 'B',
  win_next: '',
  lose_next: '',
}];
