export const FETCH_LIST_BOTS = 'FETCH_LIST_BOTS';
export const SET_LIST_BOTS = 'SET_LIST_BOTS';
export const LIST_BOTS_UPDATE_BOT_STATUS = 'LIST_BOTS_UPDATE_BOT_STATUS';

export const FETCH_BOT_HISTORY = 'FETCH_BOT_HISTORY';
export const SET_BOT_HISTORY = 'SET_BOT_HISTORY';
export const FETCH_PAY_OFF_HISTORY = 'FETCH_PAY_OFF_HISTORY';
export const SET_PAY_OF_HISTORY = 'SET_PAY_OF_HISTORY';

export const FETCH_CHART_DATA = 'FETCH_CHART_DATA';
export const SET_CHART_DATA = 'SET_CHART_DATA';
export const FETCH_DATA_CHARTS = 'FETCH_DATA_CHARTS';
export const SET_DATA_CHARTS = 'SET_DATA_CHARTS';


export const FETCH_BOT_DETAIL = 'FETCH_BOT_DETAIL';
export const SET_BOT_DETAIL = 'SET_BOT_DETAIL';
export const FETCH_BOT_HISTORY_NOW = 'FETCH_BOT_HISTORY_NOW';
export const FETCH_HISTORY_TABLE = 'FETCH_HISTORY_TABLE';
export const FETCH_BOT_GC_NOW = 'FETCH_BOT_GC_NOW';
export const FETCH_TABLE_STATUS_NOW = 'FETCH_TABLE_STATUS_NOW';

export const FETCH_MIN_PROFIT_VALUE = 'FETCH_MIN_PROFIT_VALUE';

export const CREATE_BOTS = 'CREATE_BOTS';

export const UPDATE_TABLE_NAME = 'UPDATE_TABLE_NAME';

export const PAYOUT = 'PAYOUT';

export const UPDATE_BOT_NAME = 'UPDATE_BOT_NAME';

export const UPDATE_BOT_CAMPAIGN = 'UPDATE_BOT_CAMPAIGN';

export const DELETE_BOT = 'DELETE_BOT';

export const DEFAULT = 'DEFAULT';
