export const CONFIRM_BET = 'CONFIRM_BET';
export const SCREEN_BETTING_GET_INFO_USER = 'SCREEN_BETTING_GET_INFO_USER';
export const SCREEN_BETTING_SET_INFO_USER = 'SCREEN_BETTING_SET_INFO_USER';
export const SCREEN_BETTING_RESTORE_INFO_USER = 'SCREEN_BETTING_RESTORE_INFO_USER';
export const SCREEN_BETTING_CALL_LOGOUT = 'SCREEN_BETTING_CALL_LOGOUT';
export const SCREEN_BETTING_SUB_BET = 'SCREEN_BETTING_SUB_BET';
