export const FETCH_DATA_LOBBY = 'FETCH_DATA_LOBBY';
export const SET_DATA_LOBBY = 'SET_DATA_LOBBY';
export const UPDATE_DATA_LOBBY = 'UPDATE_DATA_LOBBY';
export const RESET_DATA_LOBBY = 'RESET_DATA_LOBBY';
export const FAKE_DATA_LOBBY = 'FAKE_DATA_LOBBY';
export const UN_FAKE_DATA_LOBBY = 'UN_FAKE_DATA_LOBBY';
